app_id: "e78ff865-c13e-453c-9bbb-b077f7bb5263"
app_secret: "SJ6g:9TSqf:_3I0QRIbSNXNVTZDtjkq["
redirect: "http://localhost:8000/myapp/callback"
scopes: "openid profile offline_access user.read calendars.read calendars.ReadWrite"
authority: "https://login.microsoftonline.com/common"
authorize_endpoint: "/oauth2/v2.0/authorize"
token_endpoint: "/oauth2/v2.0/token"
