# Generated by Django 2.1.15 on 2020-04-10 18:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='action_master',
            fields=[
                ('id', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('note', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, max_length=3000, null=True)),
                ('lead_time', models.IntegerField(blank=True, db_column='lead time', null=True)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='appeal_master',
            fields=[
                ('case_number', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('appeal_name', models.CharField(blank=True, max_length=255, null=True)),
                ('structure', models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('CIRP', 'CIRP'), ('OPTIONAL', 'Optional')], max_length=10)),
                ('general_info_and_notes', models.TextField(blank=True, null=True)),
                ('stamp', models.DateTimeField(blank=True, null=True)),
                ('prrb_trk_num', models.CharField(blank=True, max_length=255, null=True)),
                ('mac_trk_num', models.CharField(blank=True, max_length=255, null=True)),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('request_date', models.DateTimeField(blank=True, null=True)),
                ('acknowledged', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='case_master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.appeal_master')),
            ],
        ),
        migrations.CreateModel(
            name='charge_master',
            fields=[
                ('charge_id', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='fi_master',
            fields=[
                ('fi_id', models.IntegerField(primary_key=True, serialize=False)),
                ('fi_name', models.CharField(blank=True, max_length=255, null=True)),
                ('fi_abbr', models.CharField(blank=True, max_length=25, null=True)),
                ('fi_juris', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='issue_master',
            fields=[
                ('issue_id', models.IntegerField(primary_key=True, serialize=False)),
                ('old_id', models.IntegerField(blank=True, null=True)),
                ('issue', models.CharField(max_length=255)),
                ('realization_weight', models.FloatField()),
                ('rep_id', models.IntegerField()),
                ('category_id', models.IntegerField()),
                ('abbreviation', models.CharField(blank=True, max_length=255, null=True)),
                ('short_description', models.TextField(blank=True, null=True)),
                ('long_description', models.TextField(blank=True, null=True)),
                ('is_groupable', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='parent_master',
            fields=[
                ('parent_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('parent_full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('corp_contact_first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('corp_contact_last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('corp_contact_street', models.CharField(blank=True, max_length=255, null=True)),
                ('corp_contact_city', models.CharField(blank=True, max_length=255, null=True)),
                ('corp_contact_zip', models.CharField(blank=True, max_length=255, null=True)),
                ('corp_contact_phone', models.CharField(blank=True, max_length=255, null=True)),
                ('corp_contact_fax', models.CharField(blank=True, max_length=255, null=True)),
                ('corp_contact_email', models.EmailField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='prov_name_master',
            fields=[
                ('provider_number', models.CharField(max_length=7, primary_key=True, serialize=False, verbose_name='Proivider Number')),
                ('provider_name', models.CharField(blank=True, max_length=255, null=True)),
                ('fye', models.CharField(blank=True, max_length=5, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('county', models.CharField(blank=True, max_length=255, null=True)),
                ('fi_number', models.CharField(blank=True, max_length=25, null=True)),
                ('is_client', models.BooleanField()),
                ('parent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.parent_master')),
            ],
        ),
        migrations.CreateModel(
            name='provider_master',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('343d573c-17ea-447a-8682-840aaef97691'), primary_key=True, serialize=False)),
                ('fiscal_year', models.IntegerField(blank=True, null=True)),
                ('npr_date', models.DateField(blank=True, null=True)),
                ('receipt_date', models.DateTimeField(blank=True, null=True)),
                ('was_added', models.BooleanField(blank=True, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('audit_adjustments', models.CharField(blank=True, max_length=255, null=True)),
                ('realization_weight', models.FloatField(blank=True, null=True)),
                ('hospcontactid', models.IntegerField(blank=True, null=True)),
                ('active_in_appeal_field', models.BooleanField(blank=True, default=True, null=True)),
                ('to', models.CharField(blank=True, max_length=7, null=True)),
                ('to_date', models.DateField(blank=True, null=True)),
                ('transmactrack', models.CharField(blank=True, max_length=255, null=True)),
                ('from_field', models.CharField(blank=True, max_length=7, null=True)),
                ('agreement', models.CharField(blank=True, max_length=255, null=True)),
                ('agree_note', models.TextField(blank=True, null=True)),
                ('provider_specific_note', models.TextField(blank=True, null=True)),
                ('case_number', models.ManyToManyField(through='app.case_master', to='app.appeal_master')),
                ('charge_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.charge_master')),
                ('issue_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.issue_master')),
                ('provider_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.prov_name_master')),
            ],
        ),
        migrations.CreateModel(
            name='prrb_contacts',
            fields=[
                ('prrb_contact_id', models.IntegerField(primary_key=True, serialize=False)),
                ('last_name', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('email_address', models.CharField(max_length=255)),
                ('appeals_general_email', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_number', models.CharField(max_length=255)),
                ('street_1', models.CharField(blank=True, max_length=255, null=True)),
                ('street_2_suite_dept', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('zip', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='rep_master',
            fields=[
                ('rep_id', models.IntegerField(primary_key=True, serialize=False)),
                ('rep', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='srg_staff_master',
            fields=[
                ('sri_staff_id', models.IntegerField(primary_key=True, serialize=False)),
                ('employee', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='state_name_master',
            fields=[
                ('state_id', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('state_name', models.CharField(blank=True, max_length=25, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='status_master',
            fields=[
                ('status_id', models.IntegerField(primary_key=True, serialize=False)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='prrb_contacts',
            name='state_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.state_name_master'),
        ),
        migrations.AddField(
            model_name='provider_master',
            name='sri_staff_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.srg_staff_master'),
        ),
        migrations.AddField(
            model_name='prov_name_master',
            name='state_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.state_name_master', verbose_name='State'),
        ),
        migrations.AddField(
            model_name='parent_master',
            name='corp_contact_state_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.state_name_master'),
        ),
        migrations.AddField(
            model_name='case_master',
            name='provider_master_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.provider_master'),
        ),
        migrations.AddField(
            model_name='appeal_master',
            name='fi_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.fi_master'),
        ),
        migrations.AddField(
            model_name='appeal_master',
            name='prrb_contact_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.prrb_contacts'),
        ),
        migrations.AddField(
            model_name='appeal_master',
            name='rep_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.rep_master'),
        ),
        migrations.AddField(
            model_name='appeal_master',
            name='status_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.status_master'),
        ),
    ]
