# Generated by Django 2.1.15 on 2020-04-10 18:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider_master',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e08cd3ef-e970-4177-a260-29410b058978'), primary_key=True, serialize=False),
        ),
    ]
