# Generated by Django 2.1.15 on 2020-04-10 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prov_name_master',
            name='fye',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
