# Generated by Django 2.1.15 on 2020-04-13 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200410_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider_master',
            name='fiscal_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='provider_master',
            name='npr_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='provider_master',
            name='receipt_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
