# Generated by Django 2.1.15 on 2020-04-13 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200413_1539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case_master',
            name='case_number',
        ),
        migrations.RemoveField(
            model_name='case_master',
            name='provider_master_id',
        ),
        migrations.RemoveField(
            model_name='case_master',
            name='provider_number',
        ),
        migrations.RemoveField(
            model_name='appeal_master',
            name='stamp',
        ),
        migrations.AddField(
            model_name='provider_master',
            name='active_in_appeal_field',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='provider_master',
            name='agree_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='provider_master',
            name='agreement',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='provider_master',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='provider_master',
            name='audit_adjustments',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='provider_master',
            name='charge_id',
            field=models.ForeignKey(default=800, on_delete=django.db.models.deletion.CASCADE, to='app.charge_master'),
        ),
        migrations.AddField(
            model_name='provider_master',
            name='from_field',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='provider_master',
            name='issue_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.issue_master'),
        ),
        migrations.AddField(
            model_name='provider_master',
            name='provider_specific_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='provider_master',
            name='sri_staff_id',
            field=models.ForeignKey(default=14, on_delete=django.db.models.deletion.CASCADE, to='app.srg_staff_master'),
        ),
        migrations.AddField(
            model_name='provider_master',
            name='to',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='provider_master',
            name='to_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='provider_master',
            name='was_added',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='appeal_master',
            name='acknowledged',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.RemoveField(
            model_name='provider_master',
            name='case_number',
        ),
        migrations.AddField(
            model_name='provider_master',
            name='case_number',
            field=models.ForeignKey(default='00-0000', on_delete=django.db.models.deletion.CASCADE, to='app.appeal_master'),
        ),
        migrations.RemoveField(
            model_name='provider_master',
            name='provider_number',
        ),
        migrations.AddField(
            model_name='provider_master',
            name='provider_number',
            field=models.ForeignKey(default='01-0001', on_delete=django.db.models.deletion.CASCADE, to='app.prov_name_master'),
        ),
        migrations.AlterField(
            model_name='provider_master',
            name='receipt_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='case_master',
        ),
    ]
