# Generated by Django 2.1.15 on 2020-04-14 03:17

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200413_1602'),
    ]

    operations = [
        migrations.CreateModel(
            name='critical_dates_master',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('critical_date', models.DateField()),
                ('response', models.TextField(blank=True, null=True)),
                ('status', models.BooleanField(blank=True, null=True)),
                ('action_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.action_master')),
            ],
        ),
        migrations.AlterField(
            model_name='appeal_master',
            name='create_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appeal_master',
            name='request_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='critical_dates_master',
            name='case_number',
            field=models.ForeignKey(default='00-0000', on_delete=django.db.models.deletion.CASCADE, to='app.appeal_master'),
        ),
    ]
