# Generated by Django 2.1.15 on 2020-04-14 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200413_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='critical_dates_master',
            name='case_number',
            field=models.CharField(max_length=7),
        ),
    ]
