# Generated by Django 2.1.15 on 2020-04-15 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20200415_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider_master',
            name='case_number',
            field=models.CharField(max_length=7),
        ),
    ]
