# Generated by Django 2.1.15 on 2020-04-20 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20200415_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='appeal_master',
            name='is_ffy',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='issue_master',
            name='long_description',
            field=models.TextField(blank=True, max_length=4000, null=True),
        ),
    ]
