# Generated by Django 2.1.15 on 2020-04-22 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20200421_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue_master',
            name='category_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='issue_master',
            name='realization_weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
