# Generated by Django 2.1.15 on 2020-04-28 21:27

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20200422_1536'),
    ]

    operations = [
        migrations.CreateModel(
            name='file_storage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('case_number', models.CharField(max_length=7)),
                ('file_type', models.CharField(choices=[('CONF', 'Appeal Submission Confirmation'), ('ACK', 'Acknowledgement & Critical Due Dates'), ('30', '30 Day Letter')], max_length=10)),
                ('file', models.FileField(upload_to='case_files/')),
            ],
        ),
        migrations.AlterField(
            model_name='prov_name_master',
            name='state_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.state_name_master'),
        ),
    ]
