# Generated by Django 2.1.15 on 2020-04-30 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20200428_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file_storage',
            name='file_type',
            field=models.CharField(choices=[('CONF', 'Appeal Submission Confirmation'), ('ACK', 'Acknowledgement & Critical Due Dates'), ('30', '30 Day Letter')], max_length=100),
        ),
    ]
